/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./core/templates/**/*.html",
    "./accounts/templates/**/*.html",
    "./social/templates/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b3c5ff",
        "tertiary-container": "#c9a900",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#bf0030",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#544600",
        "on-background": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "secondary": "#335ab4",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "primary": "#b1002c",
        "on-primary-fixed": "#40000a",
        "primary-container": "#dc143c",
        "on-surface-variant": "#5c3f3f",
        "on-primary-fixed-variant": "#920022",
        "tertiary-fixed-dim": "#e9c400",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "on-secondary-fixed-variant": "#12419b",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#ffb3b3",
        "tertiary-fixed": "#ffe16d",
        "surface-container-high": "#e7e8e9",
        "surface": "#f8f9fa",
        "outline": "#916f6e",
        "on-tertiary-container": "#4c3f00",
        "on-secondary-fixed": "#001849",
        "outline-variant": "#e6bdbc",
        "secondary-container": "#7da0ff",
        "on-secondary-container": "#003387",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "on-tertiary-fixed": "#221b00",
        "on-error-container": "#93000a",
        "surface-variant": "#e1e3e4",
        "on-primary-container": "#fff1f0",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dae1ff",
        "primary-fixed": "#ffdad9",
        "primary-fixed-dim": "#ffb3b3",
        "tertiary": "#705d00",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Be Vietnam Pro", "sans-serif"],
        "body": ["Public Sans", "sans-serif"],
        "label": ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
