# Generated by Django 5.2.7 on 2026-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_electedmember_politicalparty_manifestopoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='in_government',
            field=models.BooleanField(default=False, help_text='Is this party currently in government?'),
        ),
    ]
