# Generated by Django 5.2.7 on 2026-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_politicalparty_in_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='electedmember',
            name='oath_date',
            field=models.DateField(blank=True, help_text='Date the member took oath', null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='completion_days',
            field=models.PositiveIntegerField(blank=True, help_text='Deadline in days from oath', null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='completion_months',
            field=models.PositiveIntegerField(blank=True, help_text='Deadline in months from oath', null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='completion_years',
            field=models.PositiveIntegerField(blank=True, help_text='Deadline in years from oath', null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='oath_date',
            field=models.DateField(blank=True, help_text='Date the party/government took oath', null=True),
        ),
    ]
