# Generated by Django 5.2.7 on 2026-03-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_electedmember_oath_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('target', models.CharField(help_text='Who is this petition addressed to? e.g., Ministry of Education', max_length=300)),
                ('category', models.CharField(choices=[('governance', 'Governance'), ('infrastructure', 'Infrastructure'), ('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('rights', 'Rights'), ('other', 'Other')], default='other', max_length=20)),
                ('goal', models.PositiveIntegerField(help_text='Target number of signatures')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('achieved', 'Achieved')], default='active', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='petition_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Optional: Why do you support this petition?', null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
                'unique_together': {('petition', 'user')},
            },
        ),
    ]
