# Generated by Django 5.2.7 on 2026-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_iplocationcache_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='os_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
