# Generated by Django 5.2.7 on 2026-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_manifestopoint_is_completed_submanifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
