# Generated by Django 5.2.7 on 2026-03-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='electedmember',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='secretary_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
