# Generated by Django 5.2.7 on 2026-03-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_electedmember_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completion_days', models.PositiveIntegerField(blank=True, help_text='Deadline in days from oath', null=True)),
                ('completion_months', models.PositiveIntegerField(blank=True, help_text='Deadline in months from oath', null=True)),
                ('completion_years', models.PositiveIntegerField(blank=True, help_text='Deadline in years from oath', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elected_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.electedmember')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.politicalparty')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.commitment'),
        ),
        migrations.CreateModel(
            name='SubCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_commitments', to='core.commitment')),
            ],
        ),
    ]
