# Generated by Django 5.2.7 on 2026-04-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_commitment_activity_commitment_subcommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='category',
            field=models.CharField(blank=True, choices=[('economy', 'Economy & Finance'), ('infrastructure', 'Infrastructure & Development'), ('education', 'Education'), ('health', 'Health & Social Welfare'), ('governance', 'Governance & Administration'), ('environment', 'Environment & Climate'), ('agriculture', 'Agriculture & Rural Development'), ('technology', 'Technology & Innovation'), ('defense', 'Defense & Security'), ('foreign', 'Foreign Affairs'), ('rights', 'Rights & Justice'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='category',
            field=models.CharField(blank=True, choices=[('economy', 'Economy & Finance'), ('infrastructure', 'Infrastructure & Development'), ('education', 'Education'), ('health', 'Health & Social Welfare'), ('governance', 'Governance & Administration'), ('environment', 'Environment & Climate'), ('agriculture', 'Agriculture & Rural Development'), ('technology', 'Technology & Innovation'), ('defense', 'Defense & Security'), ('foreign', 'Foreign Affairs'), ('rights', 'Rights & Justice'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
