# Generated by Django 5.2.7 on 2026-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_commitment_category_manifestopoint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='constituency_en',
            field=models.CharField(help_text='e.g., Kathmandu-1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='constituency_ne',
            field=models.CharField(help_text='e.g., Kathmandu-1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='electedmember',
            name='name_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manifestopoint',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='target_en',
            field=models.CharField(help_text='Who is this petition addressed to? e.g., Ministry of Education', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='target_ne',
            field=models.CharField(help_text='Who is this petition addressed to? e.g., Ministry of Education', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='title_ne',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='name_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcommitment',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcommitment',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submanifesto',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submanifesto',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
