# Generated by Django 5.2.7 on 2026-04-04 15:39

from django.db import migrations
def copy_and_translate_fields(apps, schema_editor):
    
    # Models and their text fields to migrate
    models_to_translate = {
        'PoliticalParty': ['name', 'description'],
        'ElectedMember': ['name', 'constituency'],
        'ManifestoPoint': ['title', 'description'],
        'SubManifesto': ['title'],
        'Commitment': ['title', 'description'],
        'SubCommitment': ['title'],
        'Activity': ['title', 'description'],
        'Petition': ['title', 'description', 'target']
    }
    
    for model_name, fields in models_to_translate.items():
        Model = apps.get_model('core', model_name)
        
        for instance in Model.objects.all():
            updated = False
            for field in fields:
                # modeltranslation hides the original value behind the property, 
                # but during migrations we can usually access it natively or we can just 
                # extract it. In migrations, the translated fields are just columns.
                ne_field = f"{field}_ne"
                en_field = f"{field}_en"
                
                # Get raw value from the original column using __dict__ or getattr
                original_val = getattr(instance, field, None)
                ne_val = getattr(instance, ne_field, None)
                en_val = getattr(instance, en_field, None)
                
                # Copy to Nepali if not already there
                if original_val and not ne_val:
                    setattr(instance, ne_field, original_val)
                    ne_val = original_val
                    updated = True
            
            if updated:
                update_kwargs = {}
                for f in fields:
                    if getattr(instance, f"{f}_ne", None):
                        update_kwargs[f"{f}_ne"] = getattr(instance, f"{f}_ne")
                
                if update_kwargs:
                    Model.objects.filter(pk=instance.pk).update(**update_kwargs)
                
def reverse_translation(apps, schema_editor):
    pass # Cannot reverse reliably

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activity_description_en_activity_description_ne_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_and_translate_fields, reverse_code=reverse_translation),
    ]
