# Generated by Django 5.2.7 on 2026-04-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_migrate_translation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='is_completed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manifestopoint',
            name='is_completed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subcommitment',
            name='is_completed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='submanifesto',
            name='is_completed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
