# Generated by Django 5.2.7 on 2026-04-05 03:00

from django.db import migrations


def migrate_to_null(apps, schema_editor):
    ManifestoPoint = apps.get_model('core', 'ManifestoPoint')
    SubManifesto = apps.get_model('core', 'SubManifesto')
    Commitment = apps.get_model('core', 'Commitment')
    SubCommitment = apps.get_model('core', 'SubCommitment')

    ManifestoPoint.objects.filter(is_completed=False).update(is_completed=None)
    SubManifesto.objects.filter(is_completed=False).update(is_completed=None)
    Commitment.objects.filter(is_completed=False).update(is_completed=None)
    SubCommitment.objects.filter(is_completed=False).update(is_completed=None)

def reverse_migrate(apps, schema_editor):
    ManifestoPoint = apps.get_model('core', 'ManifestoPoint')
    SubManifesto = apps.get_model('core', 'SubManifesto')
    Commitment = apps.get_model('core', 'Commitment')
    SubCommitment = apps.get_model('core', 'SubCommitment')

    ManifestoPoint.objects.filter(is_completed__isnull=True).update(is_completed=False)
    SubManifesto.objects.filter(is_completed__isnull=True).update(is_completed=False)
    Commitment.objects.filter(is_completed__isnull=True).update(is_completed=False)
    SubCommitment.objects.filter(is_completed__isnull=True).update(is_completed=False)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_commitment_is_completed_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_null, reverse_migrate),
    ]
