# Generated by Django 5.2.7 on 2026-03-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('ip_address', models.GenericIPAddressField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('response_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
