# Generated by Django 5.2.7 on 2026-04-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_image_alter_userprofile_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_social',
            field=models.BooleanField(default=False, help_text='Manual override: grant this user social media post approval rights.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_verify_activities',
            field=models.BooleanField(default=False, help_text='Manual override: grant this user permanent activity verification access.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_access_granted_at',
            field=models.DateTimeField(blank=True, help_text='When dynamic verification access was last earned.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_access_override',
            field=models.BooleanField(default=False, help_text='If True, use manual can_verify_activities instead of dynamic calculation.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activity_submitted', 'Activity Submitted'), ('activity_verified', 'Activity Verified'), ('activity_approved_by', "Approved Another's Activity"), ('social_submitted', 'Social Post Submitted'), ('social_approved', 'Social Post Approved'), ('level_up', 'Level Up'), ('xp_earned', 'XP Earned'), ('access_granted', 'Verification Access Granted'), ('access_revoked', 'Verification Access Revoked'), ('manual_override', 'Manual Admin Override')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('xp_change', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
