# Generated by Django 5.2.7 on 2026-04-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('image', 'Image Post'), ('reel', 'Reel / Video')], default='image', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('caption', models.TextField(blank=True, help_text='Caption text for the social media post.')),
                ('description', models.TextField(blank=True, help_text='Short description for Template B.')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated important words for Template A yellow highlighting.')),
                ('template_choice', models.CharField(choices=[('keyword_highlight', 'Template A: Keyword Highlight'), ('red_box_title', 'Template B: Red Box Title')], default='keyword_highlight', max_length=20)),
                ('aspect_ratio', models.CharField(choices=[('1:1', 'Square (1:1) — 1080×1080'), ('4:5', 'Portrait (4:5) — 1080×1350')], default='1:1', max_length=5)),
                ('original_image', models.ImageField(blank=True, help_text='Original uploaded image (before branding).', null=True, upload_to='social/originals/')),
                ('branded_image', models.ImageField(blank=True, help_text='Pillow-generated branded image with logo, text, and date.', null=True, upload_to='social/branded/')),
                ('video_file', models.FileField(blank=True, help_text='Final reel video (merged via ffmpeg.wasm in browser).', null=True, upload_to='social/videos/')),
                ('voiceover_file', models.FileField(blank=True, help_text='Generated TTS voiceover audio file.', null=True, upload_to='social/voiceovers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('instagram_post_id', models.CharField(blank=True, max_length=100)),
                ('facebook_post_id', models.CharField(blank=True, max_length=100)),
                ('twitter_post_id', models.CharField(blank=True, max_length=100)),
                ('publish_errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_social_posts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
